// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVZ5EMXOcMK2Sll4_B3ug_RnmPPfUoTr0',
    appId: '1:943274792056:web:1d4791bdd9c138bab4c98d',
    messagingSenderId: '943274792056',
    projectId: 'app-m3',
    authDomain: 'app-m3.firebaseapp.com',
    databaseURL: 'https://app-m3-default-rtdb.firebaseio.com',
    storageBucket: 'app-m3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq_yaVdG_KyhHrOdJn-OBpsiirpIdECEA',
    appId: '1:943274792056:android:39af6c8e9cdde5fbb4c98d',
    messagingSenderId: '943274792056',
    projectId: 'app-m3',
    databaseURL: 'https://app-m3-default-rtdb.firebaseio.com',
    storageBucket: 'app-m3.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVZ5EMXOcMK2Sll4_B3ug_RnmPPfUoTr0',
    appId: '1:943274792056:web:1d4791bdd9c138bab4c98d',
    messagingSenderId: '943274792056',
    projectId: 'app-m3',
    authDomain: 'app-m3.firebaseapp.com',
    databaseURL: 'https://app-m3-default-rtdb.firebaseio.com',
    storageBucket: 'app-m3.firebasestorage.app',
  );

}